In [1]:
## Variables and data types

name = "Data Engineer"      # This is a string – text in quotes
age = 27                    # This is an integer – a whole number
is_active = True            # This is a boolean – it's either True or False
salary = 155000.50           # This is a float – a number with a decimal

In [2]:
type(is_active)

bool

Conditionals using if, elif, and else

In [3]:
is_active = False

if is_active:
    print("User is active")
else:
    print("User is inactive")

User is inactive

In [5]:
age = 25


if age <13:
  print("Child")
elif age <=19:
  print("Teenager")
elif age <= 64:
  print("Adult")
else:
  print("Senior")

Adult

## Loops

Loops let you run code multiple times.  
Use `for` when looping over items and `while` when looping until a condition is met.

In [6]:
## using for

for i in range(5):
  print("Welcome to Data Engineering")

Welcome to Data Engineering
Welcome to Data Engineering
Welcome to Data Engineering
Welcome to Data Engineering
Welcome to Data Engineering

In [7]:
## using while

i=0

while i <= 7:
  print(f"Welcome to Class - {i}")
  i += 1

Welcome to Class - 0
Welcome to Class - 1
Welcome to Class - 2
Welcome to Class - 3
Welcome to Class - 4
Welcome to Class - 5
Welcome to Class - 6
Welcome to Class - 7

Functions

In [8]:
def greeting(name):
  return f"Hello, my dear friend, {name}. It is a pleasure meeting you today"

In [9]:
greeting("Margaret")

'Hello, my dear friend, Margaret. It is a pleasure meeting you today'

Add Two Numbers

In [10]:
def add(a,b):
  return a+b

In [11]:
# print(add(10,5))

add(730,-50)

680

Basic File Handling: Read and Write a simple text using python

In [12]:
# Step 1: Writing to a file

with open("DE_File.txt", "w") as f:
    f.write("Hello")

In [13]:
# Step 2: Reading from a file

with open("DE_File.txt", "r") as f:
    content = f.read()

print(content)

Hello

Installing libaries

In [14]:
# !pip install pandas numpy

In [15]:
## pandas

import pandas as pd

# Create a simple DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Department": ["IT", "HR", "Finance"]
}

df = pd.DataFrame(data)
# print(df)
df

      Name  Age Department
0    Alice   25         IT
1      Bob   30         HR
2  Charlie   35    Finance

Reading and Writing CSV Files

In [16]:
# Save the dataframe as a csv file

df.to_csv("employees.csv", index = False)

In [17]:
# Read CSV File

df_loaded = pd.read_csv("employees.csv")

df_loaded

      Name  Age Department
0    Alice   25         IT
1      Bob   30         HR
2  Charlie   35    Finance

In [18]:
# Save the dataframe as an excel file

df.to_excel("employees.xlsx", index = False)

In [19]:
# Read Excel File

df_loaded_excel = pd.read_excel("employees.xlsx")

df_loaded_excel

      Name  Age Department
0    Alice   25         IT
1      Bob   30         HR
2  Charlie   35    Finance

Cleaning and Transforming Data: You can use `pandas` to clean messy data—remove duplicates, rename columns, or filter rows.

In [20]:
print(df)

      Name  Age Department
0    Alice   25         IT
1      Bob   30         HR
2  Charlie   35    Finance

In [21]:
# Rename Columns

df_renamed = df.rename(columns={"Department": "Dept"})

df_renamed

      Name  Age     Dept
0    Alice   25       IT
1      Bob   30       HR
2  Charlie   35  Finance

In [22]:
# Filter rows where age is >28


filtered_df = df_renamed[df_renamed["Age"] > 28]

filtered_df

      Name  Age     Dept
1      Bob   30       HR
2  Charlie   35  Finance

Handling Missing Data

In [23]:
# Add missing data

df_with_nan = df.copy()

In [24]:
df_with_nan.loc[1, "Age"] = None

In [25]:
df_with_nan

      Name   Age Department
0    Alice  25.0         IT
1      Bob   NaN         HR
2  Charlie  35.0    Finance

In [26]:
# Fill missing value
df_filled = df_with_nan.fillna(0)
df_filled

      Name   Age Department
0    Alice  25.0         IT
1      Bob   0.0         HR
2  Charlie  35.0    Finance

In [27]:
# Drop missing value
df_dropped = df_with_nan.dropna()
df_dropped

      Name   Age Department
0    Alice  25.0         IT
2  Charlie  35.0    Finance

Numpy

`numpy` provides support for large, fast numerical arrays. It’s great for performance.

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))

Array: [1 2 3 4 5]
Mean: 3.0
Max: 5

Working with Databases: Data engineers frequently move data between databases and data pipelines.

We'll start with `SQLite`, a simple built-in database that requires no setup.

`SQLite` is a lightweight, serverless database engine that stores data in a single file on your device. It supports standard SQL and is widely used for small applications, testing, and mobile development.

In [29]:
import sqlite3

#Create an in-memory SQLite databse
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

In [30]:
# Create a simple table
cursor.execute('''
    CREATE TABLE employees (
        id INTEGER PRIMARY KEY,
        name TEXT,
        department TEXT,
        salary INTEGER
    )
''')

In [31]:
## insert into the table

cursor.executemany('''
    INSERT INTO employees (name, department, salary)
    VALUES (?, ?, ?)
''', [
    ('Alice', 'IT', 70000),
    ('Bob', 'HR', 50000),
    ('Charlie', 'Finance', 80000)
])
conn.commit()

In [32]:
## querying the database

cursor.execute("SELECT * FROM employees WHERE salary > 70000")
rows = cursor.fetchall()
for row in rows:
    print(row)

(3, 'Charlie', 'Finance', 80000)

Using Pandas in SQL

In [33]:
import pandas as pd

df_sql = pd.read_sql_query("SELECT * FROM employees WHERE salary > 70000", conn)
print(df_sql)

   id     name department  salary
0   3  Charlie    Finance   80000

Writing DataFrames to SQL

In [34]:
new_employees = pd.DataFrame({
    'name': ['David', 'Ella'],
    'department': ['Marketing', 'IT'],
    'salary': [60000, 75000]
})

In [35]:
new_employees.to_sql('employees', conn, if_exists='append', index=False)

2

In [36]:
df_all = pd.read_sql_query("SELECT * FROM employees", conn)
print(df_all)

   id     name department  salary
0   1    Alice         IT   70000
1   2      Bob         HR   50000
2   3  Charlie    Finance   80000
3   4    David  Marketing   60000
4   5     Ella         IT   75000

## Data Ingestion

Reading data from APIs: APIs (Application Programming Interfaces) are sets of rules that allow different software systems to communicate, often accessed via URLs over the internet. They enable programs to request or send data to services like web servers, databases, or third-party apps.

In [37]:
import requests

# Example API call
response = requests.get("https://api.spacexdata.com/v4/launches/latest")
data = response.json()


# Display some key info
print("Mission Name:", data['name'])
print("Fairings:", data['fairings'])

Mission Name: Crew-5
Fairings: None

Reading and Writing Files: CSV, EXCEL, JSON, and XML

In [39]:
import pandas as pd

# Read a CSV file\

df_csv = pd.read_csv("employees.csv")
print(df_csv.head())

      Name  Age Department
0    Alice   25         IT
1      Bob   30         HR
2  Charlie   35    Finance

In [40]:
# Write to CSV

df_csv.to_csv("output_data.csv", index=True)

In [42]:
# Read a Excel file

df_excel = pd.read_excel("employees.xlsx")
print(df_excel.head())

      Name  Age Department
0    Alice   25         IT
1      Bob   30         HR
2  Charlie   35    Finance

In [43]:
# Write to Excel

df_excel.to_excel("output_data.xlsx", index=False)

In [50]:
## Read a JSON file

# First, create the employees.json file from the existing DataFrame 'df'
df.to_json('employees.json', orient='records', indent=4)

df_json = pd.read_json("employees.json")
print(df_json.head())

      Name  Age Department
0    Alice   25         IT
1      Bob   30         HR
2  Charlie   35    Finance

In [51]:
# Write to XML

df.to_xml("employees.xml", index=False)
print("DataFrame saved to employees.xml")

DataFrame saved to employees.xml

In [52]:
# Read an XML file

df_xml = pd.read_xml("employees.xml")
print(df_xml.head())

      Name  Age Department
0    Alice   25         IT
1      Bob   30         HR
2  Charlie   35    Finance

In [53]:
import xml.etree.ElementTree as ET

# Parse an XML file
tree = ET.parse("employees.xml")
root = tree.getroot()

In [54]:
# Loop through elements

for child in root:
    print(child.tag, child.attrib)

row {}
row {}
row {}

In [55]:
for person in root:
    person_data = {}
    for elem in person:
        person_data[elem.tag] = elem.text
    print(person_data)

{'Name': 'Alice', 'Age': '25', 'Department': 'IT'}
{'Name': 'Bob', 'Age': '30', 'Department': 'HR'}
{'Name': 'Charlie', 'Age': '35', 'Department': 'Finance'}

In [56]:
# Save DataFrame to Parquet
df_csv.to_parquet("employees.parquet")

In [57]:
# Read Parquet file

df_parquet = pd.read_parquet("employees.parquet")
print(df_parquet.head())

      Name  Age Department
0    Alice   25         IT
1      Bob   30         HR
2  Charlie   35    Finance

**Web Scraping** is the process of automatically extracting data from websites. It allows data engineers to collect large amounts of web-based information that may not be available through APIs or databases.

**BeautifulSoup** is a popular Python library used for parsing HTML and XML documents, making it easier to navigate and extract data from web pages.

In [69]:
import requests
from bs4 import BeautifulSoup

In [75]:
## Datacamp web scrap

url = "https://datasciencenigeria.org/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

In [76]:
## Find all the paragraphs

for p in soup.find_all('p'):
    print(p.text)
    print()

Data Science Nigeria





Established in 2016, Data Science Nigeria (DSN) is Africa’s foremost AI and Data Science organisation, leading in talent development and sector-specific solutions. As an established premier community of AI professionals, enthusiasts, and beginners spanning across Africa and beyond, including both Anglophone and Francophone nations, our mission is to nurture 1 million AI talents.

At DSN, we are not just shaping the workforce of tomorrow but also deploying AI solutions that will enhance the lives of 2 billion people in emerging markets. We drive the growth of AI start-ups and champion digital transformation across African organisations.

We cultivate one of Africa’s most vibrant and inclusive AI communities, spanning over 90 countries with a strong national footprint. Our thriving ecosystem connects more than 14,000 data scientists, engineers, researchers, mentors, and enthusiasts. Through active knowledge-sharing platforms, peer-to-peer mentoring, and regular events, we foster collaboration, innovation, and continuous learning that empower members to grow and contribute meaningfully to the global AI landscape.

We harness the transformative power of AI to drive positive change in society. Our AI-for-good initiatives are designed to tackle critical challenges in education, public health, agriculture, and financial inclusion. By creating solutions that are ethical, inclusive, and impact-driven, we ensure that underserved communities benefit from AI innovations that improve livelihoods, promote equity, and support sustainable development.

We equip individuals and organizations with the knowledge and practical skills needed to thrive in an AI-driven economy. Through tailored training programs, bootcamps, and certification courses, we bridge the skills gap and accelerate the readiness of professionals, educators, startups, and public institutions. Our focus on real-world application ensures that participants not only learn cutting-edge concepts but are also able to implement them effectively in their domains

We partner with private enterprises, public institutions, and nonprofits to design and implement scalable AI strategies. Our approach involves developing customized roadmaps that align with each organization’s goals, infrastructure, and market realities. From strategic planning to technical deployment, we guide stakeholders through the entire AI journey, ensuring successful adoption, operational excellence, and measurable outcomes.

We lead cutting-edge research that advances AI innovation with a focus on the unique needs and contexts of emerging markets. Our R&D efforts explore novel approaches in natural language processing, computer vision, generative AI, and machine learning applications that address real societal problems. By contributing to global AI knowledge and building locally relevant solutions, we shape the future of AI in ways that are inclusive, responsible, and impactful.

The DeepTech_Ready Upskilling Programme is a national digital skills development initiative under the 3 Million...

  The EdoDiDa Project is a flagship initiative under the Edo State Data for Governance...

Accelerated Learning Access Powered by DSN and Funded by Mastercard Foundation Learn At Home (LAH)...


						AI Hub, 33 Queen Street, Yaba, Lagos


						+234 814 000 0853


						info@datasciencenigeria.org

# Data Pipelines

Data pipelines move and transform data from one place to another on a schedule or trigger. It helps you automate and manage the data flow process.

## Writing a Reusable Python ETL Script

ETL stands for Extract, Transform, Load.

Here’s a simple ETL pipeline that reads from a CSV, processes the data, and writes it back.

In [77]:
import pandas as pd

def extract(file_path):
    return pd.read_csv(file_path)

def transform(df):
    # Convert all column names to lowercase
    df.columns = [col.upper() for col in df.columns]
    return df

def load(df, output_path):
    df.to_csv(output_path, index=False)

In [78]:
# Reusable ETL function
def etl_pipeline(input_path, output_path):
    df = extract(input_path)
    df = transform(df)
    load(df, output_path)

In [80]:
# Sample run
etl_pipeline("employees.csv", "clean_data.csv")

Logging and Error Handling: It’s important to log activities and handle errors in production pipelines.

You can use Python’s built-in `logging` module to track events in your ETL pipeline.

In [82]:
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)

def safe_etl_pipeline(input_path, output_path):

    try:
        logging.info("Starting ETL pipeline")
        df = extract(input_path)
        df = transform(df)
        load(df, output_path)
        logging.info("ETL pipeline completed successfully")

    except Exception as e:
        logging.error(f"Pipeline failed: {e}")

# Run safely
safe_etl_pipeline("employee.csv", "clean_data.csv")

ERROR:root:Pipeline failed: [Errno 2] No such file or directory: 'employee.csv'